/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as _authRouteImport } from './routes/__auth'
import { Route as _protectedIndexRouteImport } from './routes/__protected/index'
import { Route as _protectedSettingsRouteImport } from './routes/__protected/settings'
import { Route as _protectedDashboardRouteImport } from './routes/__protected/dashboard'
import { Route as _protected_adminRouteImport } from './routes/__protected/__admin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as _protectedSettingsIndexRouteImport } from './routes/__protected/settings/index'
import { Route as _protectedSettingsProfileRouteImport } from './routes/__protected/settings/profile'
import { Route as _protected_adminAdminSettingsRouteImport } from './routes/__protected/__admin/admin-settings'
import { Route as _protected_adminUserManagementIndexRouteImport } from './routes/__protected/__admin/user-management/index'
import { Route as _protected_adminTemplateManagementIndexRouteImport } from './routes/__protected/__admin/template-management/index'
import { Route as _protected_adminAdminSettingsIndexRouteImport } from './routes/__protected/__admin/admin-settings/index'
import { Route as _protected_adminUserManagementCreateUserRouteImport } from './routes/__protected/__admin/user-management/create-user'
import { Route as _protected_adminTemplateManagementCreateTemplateRouteImport } from './routes/__protected/__admin/template-management/create-template'
import { Route as _protected_adminAdminSettingsTicketTypesRouteImport } from './routes/__protected/__admin/admin-settings/ticket-types'
import { Route as _protected_adminAdminSettingsFieldsRouteImport } from './routes/__protected/__admin/admin-settings/fields'
import { Route as _protected_adminAdminSettingsTicketTypesIndexRouteImport } from './routes/__protected/__admin/admin-settings/ticket-types/index'
import { Route as _protected_adminAdminSettingsFieldsIndexRouteImport } from './routes/__protected/__admin/admin-settings/fields/index'
import { Route as _protected_adminUserManagementEditUserIdRouteImport } from './routes/__protected/__admin/user-management/edit-user.$id'
import { Route as _protected_adminAdminSettingsTicketTypesIdRouteImport } from './routes/__protected/__admin/admin-settings/ticket-types/$id'
import { Route as _protected_adminAdminSettingsFieldsIdRouteImport } from './routes/__protected/__admin/admin-settings/fields/$id'

const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRoute = _authRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedIndexRoute = _protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedSettingsRoute = _protectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedDashboardRoute = _protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _protectedRoute,
} as any)
const _protected_adminRoute = _protected_adminRouteImport.update({
  id: '/__admin',
  getParentRoute: () => _protectedRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRoute,
} as any)
const _protectedSettingsIndexRoute = _protectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedSettingsRoute,
} as any)
const _protectedSettingsProfileRoute =
  _protectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => _protectedSettingsRoute,
  } as any)
const _protected_adminAdminSettingsRoute =
  _protected_adminAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminUserManagementIndexRoute =
  _protected_adminUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminTemplateManagementIndexRoute =
  _protected_adminTemplateManagementIndexRouteImport.update({
    id: '/template-management/',
    path: '/template-management/',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminAdminSettingsIndexRoute =
  _protected_adminAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _protected_adminAdminSettingsRoute,
  } as any)
const _protected_adminUserManagementCreateUserRoute =
  _protected_adminUserManagementCreateUserRouteImport.update({
    id: '/user-management/create-user',
    path: '/user-management/create-user',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminTemplateManagementCreateTemplateRoute =
  _protected_adminTemplateManagementCreateTemplateRouteImport.update({
    id: '/template-management/create-template',
    path: '/template-management/create-template',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminAdminSettingsTicketTypesRoute =
  _protected_adminAdminSettingsTicketTypesRouteImport.update({
    id: '/ticket-types',
    path: '/ticket-types',
    getParentRoute: () => _protected_adminAdminSettingsRoute,
  } as any)
const _protected_adminAdminSettingsFieldsRoute =
  _protected_adminAdminSettingsFieldsRouteImport.update({
    id: '/fields',
    path: '/fields',
    getParentRoute: () => _protected_adminAdminSettingsRoute,
  } as any)
const _protected_adminAdminSettingsTicketTypesIndexRoute =
  _protected_adminAdminSettingsTicketTypesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _protected_adminAdminSettingsTicketTypesRoute,
  } as any)
const _protected_adminAdminSettingsFieldsIndexRoute =
  _protected_adminAdminSettingsFieldsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _protected_adminAdminSettingsFieldsRoute,
  } as any)
const _protected_adminUserManagementEditUserIdRoute =
  _protected_adminUserManagementEditUserIdRouteImport.update({
    id: '/user-management/edit-user/$id',
    path: '/user-management/edit-user/$id',
    getParentRoute: () => _protected_adminRoute,
  } as any)
const _protected_adminAdminSettingsTicketTypesIdRoute =
  _protected_adminAdminSettingsTicketTypesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => _protected_adminAdminSettingsTicketTypesRoute,
  } as any)
const _protected_adminAdminSettingsFieldsIdRoute =
  _protected_adminAdminSettingsFieldsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => _protected_adminAdminSettingsFieldsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/settings': typeof _protectedSettingsRouteWithChildren
  '/': typeof _protectedIndexRoute
  '/admin-settings': typeof _protected_adminAdminSettingsRouteWithChildren
  '/settings/profile': typeof _protectedSettingsProfileRoute
  '/settings/': typeof _protectedSettingsIndexRoute
  '/admin-settings/fields': typeof _protected_adminAdminSettingsFieldsRouteWithChildren
  '/admin-settings/ticket-types': typeof _protected_adminAdminSettingsTicketTypesRouteWithChildren
  '/template-management/create-template': typeof _protected_adminTemplateManagementCreateTemplateRoute
  '/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/admin-settings/': typeof _protected_adminAdminSettingsIndexRoute
  '/template-management': typeof _protected_adminTemplateManagementIndexRoute
  '/user-management': typeof _protected_adminUserManagementIndexRoute
  '/admin-settings/fields/$id': typeof _protected_adminAdminSettingsFieldsIdRoute
  '/admin-settings/ticket-types/$id': typeof _protected_adminAdminSettingsTicketTypesIdRoute
  '/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
  '/admin-settings/fields/': typeof _protected_adminAdminSettingsFieldsIndexRoute
  '/admin-settings/ticket-types/': typeof _protected_adminAdminSettingsTicketTypesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/': typeof _protectedIndexRoute
  '/settings/profile': typeof _protectedSettingsProfileRoute
  '/settings': typeof _protectedSettingsIndexRoute
  '/template-management/create-template': typeof _protected_adminTemplateManagementCreateTemplateRoute
  '/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/admin-settings': typeof _protected_adminAdminSettingsIndexRoute
  '/template-management': typeof _protected_adminTemplateManagementIndexRoute
  '/user-management': typeof _protected_adminUserManagementIndexRoute
  '/admin-settings/fields/$id': typeof _protected_adminAdminSettingsFieldsIdRoute
  '/admin-settings/ticket-types/$id': typeof _protected_adminAdminSettingsTicketTypesIdRoute
  '/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
  '/admin-settings/fields': typeof _protected_adminAdminSettingsFieldsIndexRoute
  '/admin-settings/ticket-types': typeof _protected_adminAdminSettingsTicketTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteWithChildren
  '/__protected': typeof _protectedRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/login': typeof _authLoginRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__protected/__admin': typeof _protected_adminRouteWithChildren
  '/__protected/dashboard': typeof _protectedDashboardRoute
  '/__protected/settings': typeof _protectedSettingsRouteWithChildren
  '/__protected/': typeof _protectedIndexRoute
  '/__protected/__admin/admin-settings': typeof _protected_adminAdminSettingsRouteWithChildren
  '/__protected/settings/profile': typeof _protectedSettingsProfileRoute
  '/__protected/settings/': typeof _protectedSettingsIndexRoute
  '/__protected/__admin/admin-settings/fields': typeof _protected_adminAdminSettingsFieldsRouteWithChildren
  '/__protected/__admin/admin-settings/ticket-types': typeof _protected_adminAdminSettingsTicketTypesRouteWithChildren
  '/__protected/__admin/template-management/create-template': typeof _protected_adminTemplateManagementCreateTemplateRoute
  '/__protected/__admin/user-management/create-user': typeof _protected_adminUserManagementCreateUserRoute
  '/__protected/__admin/admin-settings/': typeof _protected_adminAdminSettingsIndexRoute
  '/__protected/__admin/template-management/': typeof _protected_adminTemplateManagementIndexRoute
  '/__protected/__admin/user-management/': typeof _protected_adminUserManagementIndexRoute
  '/__protected/__admin/admin-settings/fields/$id': typeof _protected_adminAdminSettingsFieldsIdRoute
  '/__protected/__admin/admin-settings/ticket-types/$id': typeof _protected_adminAdminSettingsTicketTypesIdRoute
  '/__protected/__admin/user-management/edit-user/$id': typeof _protected_adminUserManagementEditUserIdRoute
  '/__protected/__admin/admin-settings/fields/': typeof _protected_adminAdminSettingsFieldsIndexRoute
  '/__protected/__admin/admin-settings/ticket-types/': typeof _protected_adminAdminSettingsTicketTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/admin-settings'
    | '/settings/profile'
    | '/settings/'
    | '/admin-settings/fields'
    | '/admin-settings/ticket-types'
    | '/template-management/create-template'
    | '/user-management/create-user'
    | '/admin-settings/'
    | '/template-management'
    | '/user-management'
    | '/admin-settings/fields/$id'
    | '/admin-settings/ticket-types/$id'
    | '/user-management/edit-user/$id'
    | '/admin-settings/fields/'
    | '/admin-settings/ticket-types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/'
    | '/settings/profile'
    | '/settings'
    | '/template-management/create-template'
    | '/user-management/create-user'
    | '/admin-settings'
    | '/template-management'
    | '/user-management'
    | '/admin-settings/fields/$id'
    | '/admin-settings/ticket-types/$id'
    | '/user-management/edit-user/$id'
    | '/admin-settings/fields'
    | '/admin-settings/ticket-types'
  id:
    | '__root__'
    | '/__auth'
    | '/__protected'
    | '/__auth/forgot-password'
    | '/__auth/login'
    | '/__auth/reset-password'
    | '/__protected/__admin'
    | '/__protected/dashboard'
    | '/__protected/settings'
    | '/__protected/'
    | '/__protected/__admin/admin-settings'
    | '/__protected/settings/profile'
    | '/__protected/settings/'
    | '/__protected/__admin/admin-settings/fields'
    | '/__protected/__admin/admin-settings/ticket-types'
    | '/__protected/__admin/template-management/create-template'
    | '/__protected/__admin/user-management/create-user'
    | '/__protected/__admin/admin-settings/'
    | '/__protected/__admin/template-management/'
    | '/__protected/__admin/user-management/'
    | '/__protected/__admin/admin-settings/fields/$id'
    | '/__protected/__admin/admin-settings/ticket-types/$id'
    | '/__protected/__admin/user-management/edit-user/$id'
    | '/__protected/__admin/admin-settings/fields/'
    | '/__protected/__admin/admin-settings/ticket-types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRoute: typeof _authRouteWithChildren
  _protectedRoute: typeof _protectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/': {
      id: '/__protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _protectedIndexRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/settings': {
      id: '/__protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _protectedSettingsRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/dashboard': {
      id: '/__protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _protectedDashboardRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/__admin': {
      id: '/__protected/__admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protected_adminRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRoute
    }
    '/__protected/settings/': {
      id: '/__protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof _protectedSettingsIndexRouteImport
      parentRoute: typeof _protectedSettingsRoute
    }
    '/__protected/settings/profile': {
      id: '/__protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof _protectedSettingsProfileRouteImport
      parentRoute: typeof _protectedSettingsRoute
    }
    '/__protected/__admin/admin-settings': {
      id: '/__protected/__admin/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof _protected_adminAdminSettingsRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/user-management/': {
      id: '/__protected/__admin/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof _protected_adminUserManagementIndexRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/template-management/': {
      id: '/__protected/__admin/template-management/'
      path: '/template-management'
      fullPath: '/template-management'
      preLoaderRoute: typeof _protected_adminTemplateManagementIndexRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/admin-settings/': {
      id: '/__protected/__admin/admin-settings/'
      path: '/'
      fullPath: '/admin-settings/'
      preLoaderRoute: typeof _protected_adminAdminSettingsIndexRouteImport
      parentRoute: typeof _protected_adminAdminSettingsRoute
    }
    '/__protected/__admin/user-management/create-user': {
      id: '/__protected/__admin/user-management/create-user'
      path: '/user-management/create-user'
      fullPath: '/user-management/create-user'
      preLoaderRoute: typeof _protected_adminUserManagementCreateUserRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/template-management/create-template': {
      id: '/__protected/__admin/template-management/create-template'
      path: '/template-management/create-template'
      fullPath: '/template-management/create-template'
      preLoaderRoute: typeof _protected_adminTemplateManagementCreateTemplateRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/admin-settings/ticket-types': {
      id: '/__protected/__admin/admin-settings/ticket-types'
      path: '/ticket-types'
      fullPath: '/admin-settings/ticket-types'
      preLoaderRoute: typeof _protected_adminAdminSettingsTicketTypesRouteImport
      parentRoute: typeof _protected_adminAdminSettingsRoute
    }
    '/__protected/__admin/admin-settings/fields': {
      id: '/__protected/__admin/admin-settings/fields'
      path: '/fields'
      fullPath: '/admin-settings/fields'
      preLoaderRoute: typeof _protected_adminAdminSettingsFieldsRouteImport
      parentRoute: typeof _protected_adminAdminSettingsRoute
    }
    '/__protected/__admin/admin-settings/ticket-types/': {
      id: '/__protected/__admin/admin-settings/ticket-types/'
      path: '/'
      fullPath: '/admin-settings/ticket-types/'
      preLoaderRoute: typeof _protected_adminAdminSettingsTicketTypesIndexRouteImport
      parentRoute: typeof _protected_adminAdminSettingsTicketTypesRoute
    }
    '/__protected/__admin/admin-settings/fields/': {
      id: '/__protected/__admin/admin-settings/fields/'
      path: '/'
      fullPath: '/admin-settings/fields/'
      preLoaderRoute: typeof _protected_adminAdminSettingsFieldsIndexRouteImport
      parentRoute: typeof _protected_adminAdminSettingsFieldsRoute
    }
    '/__protected/__admin/user-management/edit-user/$id': {
      id: '/__protected/__admin/user-management/edit-user/$id'
      path: '/user-management/edit-user/$id'
      fullPath: '/user-management/edit-user/$id'
      preLoaderRoute: typeof _protected_adminUserManagementEditUserIdRouteImport
      parentRoute: typeof _protected_adminRoute
    }
    '/__protected/__admin/admin-settings/ticket-types/$id': {
      id: '/__protected/__admin/admin-settings/ticket-types/$id'
      path: '/$id'
      fullPath: '/admin-settings/ticket-types/$id'
      preLoaderRoute: typeof _protected_adminAdminSettingsTicketTypesIdRouteImport
      parentRoute: typeof _protected_adminAdminSettingsTicketTypesRoute
    }
    '/__protected/__admin/admin-settings/fields/$id': {
      id: '/__protected/__admin/admin-settings/fields/$id'
      path: '/$id'
      fullPath: '/admin-settings/fields/$id'
      preLoaderRoute: typeof _protected_adminAdminSettingsFieldsIdRouteImport
      parentRoute: typeof _protected_adminAdminSettingsFieldsRoute
    }
  }
}

interface _authRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authLoginRoute: typeof _authLoginRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
}

const _authRouteChildren: _authRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authLoginRoute: _authLoginRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
}

const _authRouteWithChildren = _authRoute._addFileChildren(_authRouteChildren)

interface _protected_adminAdminSettingsFieldsRouteChildren {
  _protected_adminAdminSettingsFieldsIdRoute: typeof _protected_adminAdminSettingsFieldsIdRoute
  _protected_adminAdminSettingsFieldsIndexRoute: typeof _protected_adminAdminSettingsFieldsIndexRoute
}

const _protected_adminAdminSettingsFieldsRouteChildren: _protected_adminAdminSettingsFieldsRouteChildren =
  {
    _protected_adminAdminSettingsFieldsIdRoute:
      _protected_adminAdminSettingsFieldsIdRoute,
    _protected_adminAdminSettingsFieldsIndexRoute:
      _protected_adminAdminSettingsFieldsIndexRoute,
  }

const _protected_adminAdminSettingsFieldsRouteWithChildren =
  _protected_adminAdminSettingsFieldsRoute._addFileChildren(
    _protected_adminAdminSettingsFieldsRouteChildren,
  )

interface _protected_adminAdminSettingsTicketTypesRouteChildren {
  _protected_adminAdminSettingsTicketTypesIdRoute: typeof _protected_adminAdminSettingsTicketTypesIdRoute
  _protected_adminAdminSettingsTicketTypesIndexRoute: typeof _protected_adminAdminSettingsTicketTypesIndexRoute
}

const _protected_adminAdminSettingsTicketTypesRouteChildren: _protected_adminAdminSettingsTicketTypesRouteChildren =
  {
    _protected_adminAdminSettingsTicketTypesIdRoute:
      _protected_adminAdminSettingsTicketTypesIdRoute,
    _protected_adminAdminSettingsTicketTypesIndexRoute:
      _protected_adminAdminSettingsTicketTypesIndexRoute,
  }

const _protected_adminAdminSettingsTicketTypesRouteWithChildren =
  _protected_adminAdminSettingsTicketTypesRoute._addFileChildren(
    _protected_adminAdminSettingsTicketTypesRouteChildren,
  )

interface _protected_adminAdminSettingsRouteChildren {
  _protected_adminAdminSettingsFieldsRoute: typeof _protected_adminAdminSettingsFieldsRouteWithChildren
  _protected_adminAdminSettingsTicketTypesRoute: typeof _protected_adminAdminSettingsTicketTypesRouteWithChildren
  _protected_adminAdminSettingsIndexRoute: typeof _protected_adminAdminSettingsIndexRoute
}

const _protected_adminAdminSettingsRouteChildren: _protected_adminAdminSettingsRouteChildren =
  {
    _protected_adminAdminSettingsFieldsRoute:
      _protected_adminAdminSettingsFieldsRouteWithChildren,
    _protected_adminAdminSettingsTicketTypesRoute:
      _protected_adminAdminSettingsTicketTypesRouteWithChildren,
    _protected_adminAdminSettingsIndexRoute:
      _protected_adminAdminSettingsIndexRoute,
  }

const _protected_adminAdminSettingsRouteWithChildren =
  _protected_adminAdminSettingsRoute._addFileChildren(
    _protected_adminAdminSettingsRouteChildren,
  )

interface _protected_adminRouteChildren {
  _protected_adminAdminSettingsRoute: typeof _protected_adminAdminSettingsRouteWithChildren
  _protected_adminTemplateManagementCreateTemplateRoute: typeof _protected_adminTemplateManagementCreateTemplateRoute
  _protected_adminUserManagementCreateUserRoute: typeof _protected_adminUserManagementCreateUserRoute
  _protected_adminTemplateManagementIndexRoute: typeof _protected_adminTemplateManagementIndexRoute
  _protected_adminUserManagementIndexRoute: typeof _protected_adminUserManagementIndexRoute
  _protected_adminUserManagementEditUserIdRoute: typeof _protected_adminUserManagementEditUserIdRoute
}

const _protected_adminRouteChildren: _protected_adminRouteChildren = {
  _protected_adminAdminSettingsRoute:
    _protected_adminAdminSettingsRouteWithChildren,
  _protected_adminTemplateManagementCreateTemplateRoute:
    _protected_adminTemplateManagementCreateTemplateRoute,
  _protected_adminUserManagementCreateUserRoute:
    _protected_adminUserManagementCreateUserRoute,
  _protected_adminTemplateManagementIndexRoute:
    _protected_adminTemplateManagementIndexRoute,
  _protected_adminUserManagementIndexRoute:
    _protected_adminUserManagementIndexRoute,
  _protected_adminUserManagementEditUserIdRoute:
    _protected_adminUserManagementEditUserIdRoute,
}

const _protected_adminRouteWithChildren =
  _protected_adminRoute._addFileChildren(_protected_adminRouteChildren)

interface _protectedSettingsRouteChildren {
  _protectedSettingsProfileRoute: typeof _protectedSettingsProfileRoute
  _protectedSettingsIndexRoute: typeof _protectedSettingsIndexRoute
}

const _protectedSettingsRouteChildren: _protectedSettingsRouteChildren = {
  _protectedSettingsProfileRoute: _protectedSettingsProfileRoute,
  _protectedSettingsIndexRoute: _protectedSettingsIndexRoute,
}

const _protectedSettingsRouteWithChildren =
  _protectedSettingsRoute._addFileChildren(_protectedSettingsRouteChildren)

interface _protectedRouteChildren {
  _protected_adminRoute: typeof _protected_adminRouteWithChildren
  _protectedDashboardRoute: typeof _protectedDashboardRoute
  _protectedSettingsRoute: typeof _protectedSettingsRouteWithChildren
  _protectedIndexRoute: typeof _protectedIndexRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protected_adminRoute: _protected_adminRouteWithChildren,
  _protectedDashboardRoute: _protectedDashboardRoute,
  _protectedSettingsRoute: _protectedSettingsRouteWithChildren,
  _protectedIndexRoute: _protectedIndexRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRoute: _authRouteWithChildren,
  _protectedRoute: _protectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
