/**
 * JQL Abstract Syntax Tree (AST) Types
 *
 * This module defines the structure of parsed JQL queries.
 * The AST is generated by the parser and consumed by the SQL builder.
 */

// =============================================================================
// TOKEN TYPES
// =============================================================================

export enum TokenType {
  // Literals
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  IDENTIFIER = 'IDENTIFIER',

  // Operators
  EQUALS = 'EQUALS', // =
  NOT_EQUALS = 'NOT_EQUALS', // !=
  CONTAINS = 'CONTAINS', // ~
  NOT_CONTAINS = 'NOT_CONTAINS', // !~
  GREATER = 'GREATER', // >
  LESS = 'LESS', // <
  GREATER_EQ = 'GREATER_EQ', // >=
  LESS_EQ = 'LESS_EQ', // <=

  // Keywords
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT',
  IN = 'IN',
  IS = 'IS',
  WAS = 'WAS',
  CHANGED = 'CHANGED',
  EMPTY = 'EMPTY',
  NULL = 'NULL',
  ORDER = 'ORDER',
  BY = 'BY',
  ASC = 'ASC',
  DESC = 'DESC',

  // Punctuation
  LPAREN = 'LPAREN', // (
  RPAREN = 'RPAREN', // )
  COMMA = 'COMMA', // ,
  LBRACKET = 'LBRACKET', // [
  RBRACKET = 'RBRACKET', // ]

  // Special
  EOF = 'EOF',
}

export interface Token {
  type: TokenType;
  value: string;
  position: number;
  line: number;
  column: number;
}

// =============================================================================
// AST NODE TYPES
// =============================================================================

export type ASTNode =
  | BinaryExpression
  | UnaryExpression
  | ComparisonExpression
  | InExpression
  | IsExpression
  | WasExpression
  | ChangedExpression
  | FunctionCall
  | FieldReference
  | Literal
  | ListLiteral
  | OrderByClause;

export type Expression =
  | BinaryExpression
  | UnaryExpression
  | ComparisonExpression
  | InExpression
  | IsExpression
  | WasExpression
  | ChangedExpression
  | FunctionCall
  | FieldReference
  | Literal;

/**
 * Binary expression: expr AND/OR expr
 */
export interface BinaryExpression {
  type: 'BinaryExpression';
  operator: 'AND' | 'OR';
  left: Expression;
  right: Expression;
}

/**
 * Unary expression: NOT expr
 */
export interface UnaryExpression {
  type: 'UnaryExpression';
  operator: 'NOT';
  argument: Expression;
}

/**
 * Comparison expression: field op value
 * Operators: =, !=, ~, !~, >, <, >=, <=
 */
export interface ComparisonExpression {
  type: 'ComparisonExpression';
  operator: '=' | '!=' | '~' | '!~' | '>' | '<' | '>=' | '<=';
  field: FieldReference;
  value: Expression;
}

/**
 * In expression: field IN (values) or field NOT IN (values)
 */
export interface InExpression {
  type: 'InExpression';
  negated: boolean;
  field: FieldReference;
  values: ListLiteral;
}

/**
 * Is expression: field IS EMPTY/NULL or field IS NOT EMPTY/NULL
 */
export interface IsExpression {
  type: 'IsExpression';
  negated: boolean;
  field: FieldReference;
  check: 'EMPTY' | 'NULL';
}

/**
 * Was expression: field WAS value (historical)
 */
export interface WasExpression {
  type: 'WasExpression';
  field: FieldReference;
  value: Expression;
  during?: DateRange;
  before?: Expression;
  after?: Expression;
}

export interface DateRange {
  from: Expression;
  to: Expression;
}

/**
 * Changed expression: field CHANGED
 */
export interface ChangedExpression {
  type: 'ChangedExpression';
  field: FieldReference;
  from?: Expression;
  to?: Expression;
  during?: DateRange;
  before?: Expression;
  after?: Expression;
  by?: Expression;
}

/**
 * Function call: functionName(args)
 */
export interface FunctionCall {
  type: 'FunctionCall';
  name: string;
  arguments: Expression[];
}

/**
 * Field reference: fieldName or cf[10001]
 */
export interface FieldReference {
  type: 'FieldReference';
  name: string;
  isCustomField: boolean;
  customFieldId?: string;
}

/**
 * Literal value: string, number, or date
 */
export interface Literal {
  type: 'Literal';
  valueType: 'string' | 'number' | 'date' | 'duration';
  value: string | number;
  raw: string;
}

/**
 * List of values: (val1, val2, val3)
 */
export interface ListLiteral {
  type: 'ListLiteral';
  values: Expression[];
}

/**
 * ORDER BY clause
 */
export interface OrderByClause {
  type: 'OrderByClause';
  items: OrderByItem[];
}

export interface OrderByItem {
  field: FieldReference;
  direction: 'ASC' | 'DESC';
}

// =============================================================================
// QUERY RESULT
// =============================================================================

/**
 * Complete parsed JQL query
 */
export interface JQLQuery {
  where?: Expression;
  orderBy?: OrderByClause;
}

// =============================================================================
// FIELD MAPPING
// =============================================================================

/**
 * Supported JQL fields and their database mappings
 */
export interface JQLFieldMapping {
  // Field name in JQL
  jqlName: string;
  // Aliases for the field
  aliases: string[];
  // Database column or path
  dbColumn: string;
  // Table alias if needed
  tableAlias?: string;
  // Whether this is a custom field
  isCustomField: boolean;
  // Value type for validation and conversion
  valueType:
    | 'string'
    | 'number'
    | 'date'
    | 'user'
    | 'status'
    | 'priority'
    | 'issueType'
    | 'project'
    | 'sprint'
    | 'version'
    | 'component'
    | 'label'
    | 'resolution';
  // Whether this field supports text search (~)
  supportsTextSearch: boolean;
  // Whether this field supports historical queries (WAS, CHANGED)
  supportsHistory: boolean;
}

// =============================================================================
// ERROR TYPES
// =============================================================================

export class JQLSyntaxError extends Error {
  constructor(
    message: string,
    public position: number,
    public line: number,
    public column: number,
    public context?: string,
  ) {
    super(message);
    this.name = 'JQLSyntaxError';
  }
}

export class JQLSemanticError extends Error {
  constructor(
    message: string,
    public field?: string,
    public operator?: string,
  ) {
    super(message);
    this.name = 'JQLSemanticError';
  }
}
